apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    meta.helm.sh/release-name: redis-exporter
    meta.helm.sh/release-namespace: grafana-latest
  creationTimestamp: "2021-12-02T11:16:06Z"
  generation: 6
  labels:
    app: prometheus-redis-exporter
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-redis-exporter-4.6.0
    heritage: Helm
    release: redis-exporter
  name: redis-exporter-prometheus-redis-exporter
  namespace: grafana-latest
  resourceVersion: "276964438"
  uid: 6f94a9ae-35d0-42ad-b9ef-707bc68eb896
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-redis-exporter
      release: redis-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-redis-exporter
        chart: prometheus-redis-exporter-4.6.0
        heritage: Helm
        release: redis-exporter
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: redis://redis.redis.svc.cluster.local:6379
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-pwd
              name: redis-exporter-secret
        image: oliver006/redis_exporter:v1.51.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: exporter-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: prometheus-redis-exporter
        ports:
        - containerPort: 9121
          name: exporter-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: exporter-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: redis-exporter-prometheus-redis-exporter
      serviceAccountName: redis-exporter-prometheus-redis-exporter
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-02T11:16:06Z"
    lastUpdateTime: "2021-12-02T14:32:49Z"
    message: ReplicaSet "redis-exporter-prometheus-redis-exporter-75ff74f8d8" has
      successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-09-29T14:34:35Z"
    lastUpdateTime: "2022-09-29T14:34:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1